CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(20) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE scores (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        score INTEGER NOT NULL,
                        date TIMESTAMP NOT NULL,
                        CONSTRAINT fk_scores_user FOREIGN KEY (user_id) REFERENCES users(id)
);